name: Release CLI Tool and Caddy Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build-cli:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
        os: [ubuntu-latest, macos-latest]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.python-version }}-${{ matrix.os }}
          path: dist/

  build-caddy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
          - os: linux
            arch: arm64
          - os: darwin
            arch: amd64
          - os: darwin
            arch: arm64
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install xcaddy
        run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

      - name: Set binary name
        run: echo "BINARY_NAME=caddy-cloudflare-${{ matrix.os }}-${{ matrix.arch }}" >> $GITHUB_ENV

      - name: Build Caddy for ${{ matrix.os }}-${{ matrix.arch }}
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          xcaddy build \
            --with github.com/caddy-dns/cloudflare \
            --output ${{ env.BINARY_NAME }}

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BINARY_NAME }}
          path: ${{ env.BINARY_NAME }}

  publish:
    needs: [build-cli, build-caddy]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Download Python packages
        uses: actions/download-artifact@v4
        with:
          pattern: dist-*
          path: dist/
          merge-multiple: true

      - name: Download Caddy binaries
        uses: actions/download-artifact@v4
        with:
          pattern: caddy-cloudflare-*
          path: binaries/
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
            binaries/*
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 